Purge func
CollActionteam/clothing-loop pull request #284
Opened 2022-12-30 03:29 UTC by jnorlando

- Added Purge Function to users.go and added to v2 group
- Created button to utilize Purge function via api route to admin dashboard
- frontend axios return function in users.ts

2022-12-30 10:18 UTC, lil5 commented
Looking great 👍 

For now I'd like to only see comments that give extra value, comments explaining code usually doesn't.

Great work I hope I haven't been too harsh with my review.

2023-01-02 12:45 UTC, lil5 commented
There are a couple more pending changes to add

2023-01-03 17:27 UTC, lil5 requested changes
Please have a look

2023-01-03 17:27 UTC, lil5 commented on frontend/src/api/user.ts
> +export function purge(userUID: string) {
Please follow naming scheme and change to `userPurge`.

2023-01-03 17:27 UTC, lil5 commented on server/internal/controllers/users.go
> +	db.Where("user_id = ?", userID).Delete(&models.UserToken{})
@jnorlando  I'm trying where possible to keep away from using the orm and showing raw sql queries instead.
Please use the `db.Exec("")`.

This also evades the soft deletion available in some tables (see `deleted_at`)

2023-01-03 17:27 UTC, lil5 commented on server/internal/controllers/users.go
> +	db.Where("user_id = ?", userID).Delete(&models.UserToken{})
Why did you not use this sql query instead? To my knowladge it is generally more efficient to use a single db query than multiple.

```sql
DELETE FROM chains
WHERE id IN (
	SELECT uc.chain_id 
	FROM  user_chains AS uc
	GROUP BY uc.chain_id 
	HAVING COUNT(uc.id) = 1 AND uc.chain_id IN (
		SELECT uc2.chain_id
		FROM user_chains AS uc2
		WHERE uc2.is_chain_admin = TRUE AND uc2.user_id = ?
	)
)
```

2023-01-04 03:48 UTC, lil5 requested changes
Almost there

2023-01-04 03:58 UTC, lil5 commented
I've added a GitHub [action](https://github.com/CollActionteam/clothing-loop/blob/main/.github/workflows/lint.yml) that runs each time you push to the PR to test for Lint problems.

If your commit has a red ❌ run `npm run lint` or `make lint`

2023-01-04 15:39 UTC, jnorlando commented on server/internal/controllers/users.go
> +	}
I used auth.AuthenticateUserOfChain, for authentication since it already had the the check for is user executing the function same as query user

2023-01-05 10:57 UTC, lil5 approved these changes

2023-01-05 11:01 UTC, merged

2023-01-05 11:05 UTC, lil5 commented on frontend/src/pages/AdminDashboard.tsx
> +            userPurge(authUser!.uid);
@jnorlando `!` Fixes the typescript error, this is generally a dangerous move as it ignores the fact that `authUser` could be null.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

2023-01-05 11:06 UTC, lil5 commented on frontend/src/pages/AdminDashboard.tsx
> +              className="btn btn-link text-base block h-auto mb-4 text-black"
`h-auto` overrides the height css from the `btn` class

2023-01-05 11:07 UTC, lil5 commented on frontend/src/pages/AdminDashboard.tsx
> -            <div className="relative align-bottom">
unnecessary see https://github.com/CollActionteam/clothing-loop/pull/284/commits/4e3db76c0ba9e8c36dfc52bf6bf7f07e49a74abd#r1062358128

2023-01-05 11:11 UTC, lil5 commented on server/internal/controllers/users.go
> +	ok, user, _, _ := auth.AuthenticateUserOfChain(c, db, "", query.UserUID)
The second result of `AuthenticateUserOfChain` is the user related to `query.UserUID`

An empty `""` is very different to `" "`

2023-01-05 11:19 UTC, lil5 commented on server/internal/controllers/users.go
> +	chainIDsToDelete := []uint{}
Note how I'm using `[]uint{}` this defines and initializes `chainIDsToDelete`

GoLang is tricky as basic types default to `0` or and empty string while pointers and slices default to `nil`

```go
var i int // => 0
var s string // => ""
var p *string // => nil
var a []int // => nil
var o struct{ID int} // => {ID: 0}

i := 0 // => 0
s := "" // => ""
p := &s // => *("")
a := []int{1,2} // => [1,2]
o := struct{ID int}{ID: 1} // => {ID: 1}
```

2023-01-05 11:21 UTC, lil5 commented on server/internal/controllers/users.go
> +	tx := db.Begin()
See https://gorm.io/docs/transactions.html#Control-the-transaction-manually

2023-01-05 11:22 UTC, lil5 commented
@jnorlando Congrats on your first merge!